/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:795c4192-77b6-4f58-8c3c-d459687013ee",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_hvsLPqOIv",
    "aws_user_pools_web_client_id": "4sdo2ti7u4b5uk0he15khuhq3j",
    "oauth": {},
    "aws_user_files_s3_bucket": "ninja-notes-upload112711-dev203905-dev",
    "aws_user_files_s3_bucket_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://5qnd5hjd4jbqnauohveoavh6ny.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
